Allow locales
theam/spree_static_content pull request #1
Opened 2018-03-26 11:33 UTC by gonzalogarciajaubert

Support internationalized links

2018-03-27 10:31 UTC, alvaroloes requested changes

2018-03-27 10:31 UTC, alvaroloes commented on app/controllers/spree/static_content_controller.rb
> +      path.remove!("/#{locale}") if !locale.blank? && (I18n.available_locales.map(&:to_s).include?(locale))
Si la idea de estas líneas es borrar el `locale` del path, ¿por qué no hacerlos de forma similar a la línea 20 del modelo StaticPage? Es más simple (abajo, en este PR, ver comentarios)

2018-03-27 10:31 UTC, alvaroloes commented on lib/spree_static_content.rb
> +      %w(es fr en).each {|locale| path.sub!("/#{locale}", '')}
Para no poner las "locales" explícitamente, se podría usar `I18n.available_locales.each ...`

2018-03-27 10:31 UTC, alvaroloes commented on config/routes.rb
> +    get '/*path', to: 'static_content#show', as: 'static'
Después de hablar con @itrion, creo que todo el resto del código se puede borrar si definimos esta ruta como:
```ruby
get '(/:locale)/*path', to: 'static_content#show', as: 'static'
```

2018-03-28 14:10 UTC, gonzalogarciajaubert commented on lib/spree_static_content.rb
> +      %w(es fr en).each {|locale| path.sub!("/#{locale}", '')}
Si, no conocía el available_locales hasta que me lo comentó Johan justo antes de comitear y solo lo usé en la otra clase, lo cambio

2018-03-28 14:13 UTC, gonzalogarciajaubert commented on config/routes.rb
> +    get '/*path', to: 'static_content#show', as: 'static'
esto no se si lo entiendo bien, si defines la ruta así el request.path que llega a spree_static_content sigue siendo por ejemplo: `/es/payment` por lo que el código anterior no veo como se podría borrar me estoy perdiendo algo?

2018-04-02 09:15 UTC, itrion approved these changes

2018-04-02 09:15 UTC, itrion commented on config/routes.rb
> +    get '/*path', to: 'static_content#show', as: 'static'
Tienes razón, eso no lo elimina de la ruta

2018-04-02 10:18 UTC, alvaroloes commented on config/routes.rb
> +    get '/*path', to: 'static_content#show', as: 'static'
Yes! se me fue la bola porque creía que en el código se estaba accesdiento al **parámetro** definido en la ruta con el wildcard, es decir, a `params[:path]`. Sorry!

Entonces, no es que se pueda borrar todo el código, sino las líneas que borran la locale si usas `params[:path]` en vez de `request.path`.

Es decir, bastaría con usar `(...).find_by!(slug: params[:path])` en el método "show" y `(...).find_by_slug(params[:path]).nil?` en el método "self.matches?". De esta forma, la parte del locale se ignora automáticamente 😃

2018-04-02 11:58 UTC, gonzalogarciajaubert commented on config/routes.rb
> +    get '/*path', to: 'static_content#show', as: 'static'
Ah genial tio, ya lo modifiqué para usar el params. Al final el locale no hizo falta añadirlo en el route ya que el ya lo separa

`Parameters: {"path"=>"payment", "locale"=>"es"}`

2018-04-02 15:06 UTC, alvaroloes commented on config/routes.rb
> +    get '/*path', to: 'static_content#show', as: 'static'
Cojonudo!

2018-04-02 15:06 UTC, alvaroloes approved these changes
¡Quedó de arte! Gracias por aguantar mis comentarios!

2018-04-03 07:43 UTC, gonzalogarciajaubert commented
Al contrario @alvaroloes , gracias a tí por tu paciencia!

2018-04-03 07:43 UTC, merged